<?php

namespace Tests;

use App\Models\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use JMac\Testing\Traits\AdditionalAssertions;

abstract class TestCase extends BaseTestCase
{
    use AdditionalAssertions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->adminUser = User::factory()->create(['email' => 'admin@admin.com']);

        // honeypot should be disabled in end-to-end tests: https://github.com/spatie/laravel-honeypot?tab=readme-ov-file#disabling-in-testing
        //config()->set('honeypot.enabled', false);
    }
}
