name: Format
on:
    pull_request:
        branches: [main]
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v2
              with:
                  node-version: '18.x'

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
                  coverage: none

            - name: Install dependencies
              run: composer create-project laravel/laravel your-project-name 11.0.* --no-interaction --prefer-dist --optimize-autoloader

            - run: npm ci
            - run: npm run prepare
            - run: npm run format
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply formatting changes
                  branch: ${{ github.head_ref }}
